//import './components/gz-badge/gz-badge';
import './components/gz-for/gz-for.js';
import './components/list-lists/list-lists.js';
import './components/list-item/list-item.js';
import './components/list-item-detail/list-item-detail';
import './components/list-items/list-items.js';
import './components/list-list/list-list.js';
import './components/gz-if/gz-if.js';
import './components/gz-back/gz-back.js';
